version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: akalanka28
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    # networks:
    #   - postgres

  driver-service:
    build: ./driver-service
    ports:
      - "8082:8082" 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/driver_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: akalanka28
    depends_on:
      - postgres

  order-assignment-service:
    build: ./order-assignment-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/order_assignment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: akalanka28
      DRIVER_SERVICE_URL: http://driver-service:8082
    depends_on:
      - postgres
      - driver-service

  tracking-service:
    build: ./tracking-service
    ports:
      - "8084:8084"
    environment:
      - NODE_ENV=development
      - PORT=8084
      - MONGO_URI=mongodb://mongodb:27017/tracking_db
      - REDIS_URL=redis://redis:6379
      - DRIVER_SERVICE_URL=http://driver-service:8082
      - ORDER_ASSIGNMENT_SERVICE_URL=http://order-assignment-service:8083
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis
      - driver-service
      - order-assignment-service

volumes:
  pgdata:
  mongodb_data:
  redis_data: